language: node_js
node_js:
  - "node"
  - "10"
  - "9"
  - "8"

before_install:
    # note
    - echo "before install"
install:
    - echo "install"
    - "npm install"
script:
    - "npm run test"
    - "npm run ci:sendCoverage"
    - "npm run esdoc"
deploy:
  local-dir: docs
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
    node: '10'