language: node_js
node_js:
  - "node"
  - "10"
  - "9"
  - "8"

before_install:
    # note
    - echo "before install"
install:
    - echo "install"
    - "npm install"
script:
    - "npm run test"
    - "npm run ci:sendCoverage"
